#!$PREFIX/bin/bash
rm -rf instashell*
clear
echo -e "\e[34m Installing core packages.....\e[0m"
apt install update -y >/dev/null 2>&1
apt install upgrade -y >/dev/null 2>&1
apt install wget -y >/dev/null 2>&1
apt install tor -y >/dev/null 2>&1
apt install curl -y >/dev/null 2>&1
apt install openssl -y >/dev/null 2>&1
apt install openssl-tool -y >/dev/null 2>&1
apt install ruby -y >/dev/null 2>&1
gem install lolcat -y >/dev/null 2>&1
gem install figlet -y >/dev/null 2>&1
wget https://raw.githubusercontent.com/CodyAvi/igbypass/master/instashell >/dev/null 2>&1
cd $PREFIX/etc/tor >/dev/null 2>&1
rm -rf torrc
wget https://raw.githubusercontent.com/CodyAvi/files/master/torrc >/dev/null 2>&1
cd >/dev/null 2>&1

(trap '' SIGINT SIGTSTP && command -v tor > /dev/null 2>&1 || { printf >&2  "\e[1;92mInstalling TOR, please wait...\n\e[0m"; apt-get update > /dev/null && apt-get -y install tor > /dev/null || printf "\e[1;91mTor Not installed.\n\e[0m"; }) & wait $!

(trap '' SIGINT SIGTSTP && command -v openssl > /dev/null 2>&1 || { printf >&2  "\e[1;92mInstalling openssl, please wait...\n\e[0m"; apt-get update > /dev/null && apt-get -y install openssl > /dev/null || printf "\e[1;91mOpenssl Not installed.\n\e[0m"; }) & wait $! 

(trap '' SIGINT SIGTSTP && command -v curl > /dev/null 2>&1 || { printf >&2  "\e[1;92mInstalling cURL, please wait...\n\e[0m"; apt-get update > /dev/null && apt-get -y install curl > /dev/null || printf "\e[1;91mCurl Not installed.\n\e[0m"; }) & wait $!

printf "\e[1;92mAll Requires are installed!\n\e[0m"
echo -e "\e[34m Installation Successful!!\e[0m"
rm -rf setup*
figlet Enjoy!! | lolcat
sleep 4
clear
bash instashell
